name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Cache Cargo
        if: "!startsWith(github.ref, 'refs/tags/v')"
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: nix develop --command cargo build --verbose --color always
